version: '3.8'
services:
  quiz-api:
    build:
      context: .
    ports:
      - 9090:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbserver/quiz
      - SPRING_DATASOURCE_USERNAME=quizuser
      - SPRING_DATASOURCE_PASSWORD=123456

  dbserver:
    image: postgres:13.3-alpine
    ports:
      - 5423:5432
    environment:
      - POSTGRES_DB=quiz
      - POSTGRES_USER=quizuser
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
