drop table if exists users CASCADE;

create table users (id bigint generated by default as identity, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, date_of_birth date, email varchar(255) not null, enabled boolean not null, first_name varchar(255), gender smallint, last_name varchar(255), password varchar(255) not null, role integer not null, updated_at timestamp, username varchar(255) not null, primary key (id));

-- alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
-- alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username)
