drop table if exists category CASCADE;

create table category (id bigint generated by default as identity, created_at timestamp, name varchar(255), updated_at timestamp, primary key (id));

alter table category add constraint UK_46ccwnsi9409t36lurvtyljak unique (name);
