drop table if exists quiz CASCADE;

create table quiz (id bigint generated by default as identity, created_at timestamp, name varchar(255), time_limit integer, updated_at timestamp, category_id bigint, primary key (id));

alter table quiz add constraint FK82x9fxd5tsbb3i1ewrp3cr8xa foreign key (category_id) references category;
alter table quiz add constraint UK_imux4m190glnqxeh8gapkk2t unique (name)
