drop table if exists question CASCADE;

create table question (id bigint generated by default as identity, created_at timestamp, text varchar(255), time_limit integer, updated_at timestamp, value tinyint, quiz_id bigint, primary key (id));

alter table question add constraint UK_6e4u3c940r1mbptri301qma0i unique (text);
alter table question add constraint FKb0yh0c1qaxfwlcnwo9dms2txf foreign key (quiz_id) references quiz;

