drop table if exists answer CASCADE;

create table answer (id bigint generated by default as identity, correct boolean not null, created_at timestamp, text varchar(255), updated_at timestamp, question_id bigint, primary key (id));

alter table answer add constraint FK8frr4bcabmmeyyu60qt7iiblo foreign key (question_id) references question;
