drop table if exists user_quiz CASCADE;

create table user_quiz (id bigint generated by default as identity, created_at timestamp, updated_at timestamp, quiz_id bigint, user_id bigint, primary key (id));

alter table user_quiz add constraint FKamnut7xcu11shpwa926626y87 foreign key (quiz_id) references quiz;
alter table user_quiz add constraint FKeuoc6oyjhqpnqf4iufs0j6t8b foreign key (user_id) references users;
