create table country (id bigint generated by default as identity, alpha2code varchar(2) not null, alpha3code varchar(3) not null, area float, capital varchar(100), create_date timestamp not null, flag varchar(100), name varchar(100) not null, population bigint, region varchar(100) not null, subregion varchar(100) not null, update_date timestamp not null, primary key (id));

alter table country add constraint UK_837jcu5oc26d8y6yfyuek3m7l unique (alpha2code);
alter table country add constraint UK_1yc0rjqnvkobrtvvqjxgbhyiy unique (alpha3code);
alter table country add constraint UK_llidyp77h6xkeokpbmoy710d4 unique (name);
